name: "01-EKS"
on:
  workflow_dispatch:
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read

jobs:
  Plan:
    uses: RekhuGopal/aws_eks_labs/.github/workflows/aws_tf_plan.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

  Apply:
    needs: Plan
    uses: RekhuGopal/aws_eks_labs/.github/workflows/aws_tf_appy.yml@main
    with:
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}