### Reusable workflow to download terraform artifact built by `az_tf_plan` and apply the artifact/plan ###
name: "02-ELKStack"
on:
  workflow_dispatch:
jobs:
  deploy-elkstack:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform destroy
        run: terraform destroy -auto-approve
